root/Models/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Resources;
using System.Web;
using MarcBachraty.LocalResource;


namespace MarcBachraty.Models
{
	public class ContactViewModel
	{
		[Required]
		[Display(Name = "firstname", ResourceType = typeof(forms))]  
		public string FirstName { get; set; }

        [Display(Name = "surname", ResourceType = typeof(forms))]  
		public string SurName { get; set; }
		[Display(Name = "city", ResourceType = typeof(forms))]
		public string City { get; set; }
		
		[StringLength(2500, MinimumLength = 1)]
		[DataType(DataType.MultilineText)]
		[Display(Name = "comments", ResourceType = typeof(forms))]
		public string Comments { get; set; }

		[UIHint("_DDRegarding")]
		[Display(Name = "contactreason", ResourceType = typeof(forms))]  
		public string ContactReason { get; set; }

		[Display(Name = "dojo", ResourceType = typeof(forms))]
		public string Dojo { get; set; }
		[EmailAddress]
		[DataType(DataType.EmailAddress)]
		[Display(Name = "email", ResourceType = typeof(forms))]
		public string Email { get; set; }

		[Display(Name = "phone", ResourceType = typeof(forms))]
		public string Phone { get; set; }

		[Display(Name = "street", ResourceType = typeof(forms))]
		public string Street { get; set; }

		[Display(Name = "website", ResourceType = typeof(forms))]
		public string Website { get; set; }

		[Display(Name = "zip", ResourceType = typeof(forms))]
		public string Zip { get; set; }
		public int NoA { get; set; }
		public int NoB { get; set; }

        [Required]
        public int CaptchaCheck { get; set; }

        public string MessageHeader { get; set; }
        public string Message { get; set; }
        public string Status { get; set; }

    }

    //[Required]
    //[StringLength(200, MinimumLength = 2)]
    //public string Name { get; set; }

    //[Required]
    //[EmailAddress]
    //[DataType(DataType.EmailAddress)]
    //[Display(Name = "Email address")]
    //public string EmailAddress { get; set; }

    //[Required]
    //[StringLength(2500, MinimumLength = 10)]
    //[DataType(DataType.MultilineText)]
    //public string Message { get; set; }
    //}
}

root/Controllers/ContactController.cs
using System;
using System.Configuration;
using System.Linq;
using System.Web.Mvc;
using System.Web.WebPages;
using MarcBachraty.Classes;
using MarcBachraty.LocalResource;
using MarcBachraty.Models;
using Umbraco.Web.Mvc;

namespace MarcBachraty.Controllers
{
	public class ContactController : SurfaceController
	{
		public ActionResult RenderContactForm()
		{
		    var model = new ContactViewModel
		    {
		        NoA = new Random().Next(1, 3),
		        NoB = new Random().Next(1, 11)
		    };

		    return View("_contactForm", model);
		}

		[HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult HandleContactForm(ContactViewModel model)
		{
		    var msg = new CallResponse();
            var capchaCheck = model.CaptchaCheck;

		    var nA = model.NoA;

		    var nB = model.NoB;
            if (capchaCheck ==0)
            {
                msg.Message = "Add the nubers displayed above the field";
                return Json(msg, JsonRequestBehavior.AllowGet);
            }


            if (capchaCheck != (nA + nB))
		    {
		        msg.Message = Errors.captchaerror;
		        return Json(msg, JsonRequestBehavior.AllowGet);
            }
		    if (!ModelState.IsValid)
		    {
		        var errors = ModelState.Where(x => x.Value.Errors.Count > 0)
		            .Select(x => new { x.Key, x.Value.Errors })
		            .ToArray();
		        msg.Status = Status.ModelStateNotValid.ToString();
		        msg.Message = errors.Aggregate("", (current, error) => current + error.ToString()); ;
		        return Json(msg, JsonRequestBehavior.AllowGet);
		    }

		    try
		    {
		        if (ModelState.IsValid)
		        {
                    var body = forms.fullname + ": " + model.FirstName + " " + model.SurName + "<br>" +
		                       forms.dojo + ": "
		                       + model.Dojo + "<br>" + model.Email + "<br>" + model.Phone + "<br>" + model.City + "<br>" +
		                       forms.comments + ": " + model.Comments; 
		            EmailGateway.SendMail(model.Email, ConfigurationManager.AppSettings["contactEmailAddress"], "From web", body, true);
		            msg.Status = Status.Ok.ToString();
		            msg.MessageHeader = string.Format(forms.retcontactheader, model.FirstName+" "+model.SurName);
		            msg.Message = forms.retcontactmessage;
		        }
		    }
		    catch (Exception ex)
		    {
		        msg.Status = Status.ModelStateNotValid.ToString();
		        msg.Message = "unexpected error occured: "+ex.Message+"<br/>"+ex.InnerException;
		        return Json(msg, JsonRequestBehavior.AllowGet);
		    }
		    return Json(msg, JsonRequestBehavior.AllowGet);

		}
	}
}

root/Views/Contact.cshtml
@using System.Globalization
@using MarcBachraty.Models
@inherits UmbracoTemplatePage
@{
	Layout = "umbLayout.cshtml";
	// If the editor has not explicitly provided the "Page title" property page
	// then just show the name of the page otherwise show the provided title
	var pageTitle = string.IsNullOrWhiteSpace(CurrentPage.Title)
		? CurrentPage.Name
		: CurrentPage.Title;

}
@{ Html.RenderPartial("_banner"); }


<!-- Main -->
<div id="main">
	<div class="container">
		<div class="row">

			<!-- Content -->
			<div id="content" class="8u skel-cell-important">
				<section>
					<header>
						<h2>@pageTitle</h2>
						@if (CurrentPage.HasValue("image"))
						{
							<span class="image image-full"><img src="@Umbraco.Media(CurrentPage.image.ToString()).umbracoFile" alt="" /></span>
						}

					</header>

					@if (CurrentPage.HasValue("image"))
					{

						<img class="image left" width="20%" src="@Umbraco.Media(CurrentPage.image.ToString()).umbracoFile" alt="" />

					}

					@CurrentPage.bodyText
					@{
						
							<div class="row">
								<div class="large-8 medium-7 small-12 columns">
									@Html.Action("RenderContactForm", "Contact")
								</div>
							</div>
					
					}

				</section>
			</div>
			<!-- Sidebar -->
			<div id="sidebar" class="4u">
				<section>
					<header>
						<h2>@CurrentPage.rightHeader</h2>
					</header>
					<div class="row">
						@CurrentPage.rightText
						@{

							var multiUrlPickerDyn1 = CurrentPage.bulletlist1;
							if (multiUrlPickerDyn1.Any())
							{
								<section class="6u">

									<ul class="default">
										@foreach (var item in multiUrlPickerDyn1)
										{
											<li><a href="@item.Url" target="@item.Target">@item.Name</a></li>

										}

									</ul>
								</section>
							}
						}
						@{
							var multiUrlPickerDyn2 = CurrentPage.bulletlist2;
							if (multiUrlPickerDyn2.Any())
							{
								<section class="6u">
									<ul class="default">
										@foreach (var item in multiUrlPickerDyn2)
										{
											<li><a href="@item.Url" target="@item.Target">@item.Name</a></li>

										}

									</ul>
								</section>
							}
						}

					</div>
				</section>
				<section>
					@{Html.RenderPartial("_UpcomingSeminars");}
				</section>
			</div>

		</div>
	</div>
</div>
<!-- /Main -->

root/Views/MediaPage.cshtml
@using System.Globalization
@using YouTube.Models
@inherits UmbracoTemplatePage
@{
    Layout = "umbLayout.cshtml";

    // If the editor has not explicitly provided the "Page title" property page
    // then just show the name of the page otherwise show the provided title
    var pageTitle = string.IsNullOrWhiteSpace(CurrentPage.Title)
        ? CurrentPage.Name
        : CurrentPage.Title;
    

   
}
	@{ Html.RenderPartial("_banner"); }


<!-- Main -->
<div id="main">
    <div class="container">
        <div class="row">

            <!-- Content -->
            <div id="content" class="8u skel-cell-important">
                <section>
                    <header>
                        <h2>@pageTitle</h2>
                       @if (CurrentPage.Ancestors().Any())
                       {
                        <ul class="breadcrumb">
                            @* For each page in the ancestors collection which have been ordered by Level (so we start with the highest top node first) *@
                            @foreach (var page in CurrentPage.Ancestors().OrderBy("Level"))
                            {
                                <li><a href="@page.Url">@page.Name</a> <span class="divider">/</span></li>
                            }
                            @* Display the current page as the last item in the list *@
                            <li class="active">@CurrentPage.Name</li>
                        </ul>
                       }
                        <span class="byline">@CurrentPage.byline</span>
                       
                      
                    </header>
                   
                   
                    
                        @CurrentPage.bodyText
                       
</section>
                    </div>
            <!-- Sidebar -->
            <div id="sidebar" class="4u">
                <section>
                    <header>
                        <h2>Videos</h2>
                    </header>
                    <div class="row">
                        <section class="6u">
                            <ul class="default">
                                @foreach (var typedVideo in Model.Content.GetPropertyValue<YouTube>("youtubeChannel"))
                                {
                                    <li>
                                        @Html.Raw(typedVideo.Player.EmbedHtml)<br/>
                                       @typedVideo.Snippet.Title, Views: @typedVideo.Statistics.ViewCount
                                   
                                </li>
                                }
                                </ul></section>
                    </div>
                </section>

            </div>
            

        </div>
    </div>
</div>
<!-- /Main -->

root/Views/SeminarsOverview.cshtml
@using System.Globalization
@inherits UmbracoTemplatePage
@{
    Layout = "umbLayout.cshtml";
    var pageTitle = string.IsNullOrWhiteSpace(CurrentPage.Title)
        ? CurrentPage.Name
        : CurrentPage.Title;
}
@{ Html.RenderPartial("_banner"); }
<style>
    .clearfix {
  overflow: auto;
}
</style>
<div id="main">
    <div class="container">
        <div class="row">

            <div id="content" class="8u skel-cell-important">
                <section>
                    <header>
                        <h2>@pageTitle</h2>
                        @if (CurrentPage.HasValue("image"))
                        {
                            var id = Umbraco.TypedMedia(CurrentPage.GetPropertyValue("image")).Id;
                            var spotimg2 = Umbraco.TypedMedia((int)id);
                            <span class="image image-full">
                                <img src="@spotimg2.Url" alt="@CurrentPage.Name" />
                                
                            </span>
                        }

                    </header>
                    <article>
                        @{
                            var helper = new UmbracoHelper(UmbracoContext.Current);

                            IPublishedContent root = helper.Content(1068);
                            IPublishedContent eventRoot = helper.Content(Convert.ToInt32(root.GetProperty("seminars").Value));
                            foreach (var item in eventRoot.Children.Where("Visible").Where("end >= DateTime.Now.Date").OrderBy("start"))
                            {
                                if (Convert.ToDateTime(item.GetProperty("end").Value) > DateTime.Now)
                                {
                                    <section>
                                           
                                        <h3><a href="@item.Url">@item.GetProperty("SubHeader").Value</a></h3>
                                        
                                        <ul class="meta">
                                            <li class="timestamp">@Convert.ToDateTime(item.GetProperty("start").Value).ToString("f", CultureInfo.CreateSpecificCulture("en-US"))</li>
                                        </ul>
                                        <div class="clearfix">
                                            @if (item.HasValue("image"))
                                            {
                                                <a href="@item.Url">
                                                    <img class="image left" src="@Umbraco.Media(item.GetPropertyValue("image").ToString()).GetResponsiveImageUrl(170, 0)" alt="" />
                                                </a>
                                            }
                                            @Umbraco.Truncate(item.GetProperty("BodyText").Value.ToString(), 150)
                                            @if (item.HasValue("seminarPoster"))
                                            {
                                                var id = Umbraco.TypedMedia(item.GetPropertyValue("seminarPoster")).Id;
                                                var media = Umbraco.TypedMedia((int)id);
                                                <p>Seminarposter here: <a href="@media.Url">Poster</a></p>
                                            }
                                            <a href="@item.Url" class="button">Continue Reading</a>
                                        </div>
                                    </section>
                                }
                            }
                        }
                    </article>
                    <!-- /Content -->
                </section>
            </div>

            <!-- Sidebar -->
            <div id="sidebar" class="4u">
                <section>
                    <header>
                        <h2>@CurrentPage.rightHeader</h2>
                    </header>
	                @*<div class="row">
						<h3>Next seminar: </h3> 
						@{
							foreach (var itm in eventRoot.Children.Where("Visible").Where("end >= DateTime.Now.Date").OrderBy("start").Take(1))
							{
								if (Convert.ToDateTime(itm.GetProperty("end").Value) > DateTime.Now)
								{
									<section class="4u">
										<a class="image full" href="@itm.Url">
											@if (itm.HasValue("image"))
											{
												<div class="clip"><img src="@Umbraco.Media(itm.GetProperty("image").Value.ToString()).umbracoFile" alt="" /></div>
											}
											<header>
												<h3>@Convert.ToDateTime(itm.GetProperty("start").Value).ToString("f", CultureInfo.CreateSpecificCulture("en-US")) @itm.GetProperty("subheader").Value</h3>
											</header>
											@Umbraco.Truncate(itm.GetProperty("bodyText").Value.ToString(), 40)
										</a>
									</section>
								}
							}
						}
</div>*@
                </section>
              
            </div>

        </div>
    </div>
</div>

root/Views/SingleSeminar.cshtml
@inherits UmbracoTemplatePage
@{
    Layout = "umbLayout.cshtml";
    // If the editor has not explicitly provided the "Page title" property page
    // then just show the name of the page otherwise show the provided title
    dynamic pageTitle = string.IsNullOrWhiteSpace(CurrentPage.Title)
        ? CurrentPage.Name
        : CurrentPage.Title;
    
}
@{ Html.RenderPartial("_banner"); }




<!-- Main -->
<div id="main">
	<div class="container">
		<div class="row">

			<!-- Content -->
			<div id="content" class="8u skel-cell-important">
				<section>
					<header>
						<h2>@pageTitle</h2>
                        
					</header>
                    
					<ul class="meta"><li>@CurrentPage.SubHeader</li>
						<li class="timestamp">@CurrentPage.start.ToString("f")</li>
					</ul>
					@if (CurrentPage.HasValue("image"))
                    {
                        var id = Umbraco.TypedMedia(CurrentPage.GetPropertyValue("image")).Id;
                        var spotimg2 = Umbraco.TypedMedia((int)id);
                        <img src="@spotimg2.Url" alt="@CurrentPage.Name" style="width: 30%" />
					}
					@if (CurrentPage.HasValue("seminarPoster"))
                    {
                        var id = Umbraco.TypedMedia(CurrentPage.GetPropertyValue("seminarPoster")).Id;
                        var media = Umbraco.TypedMedia((int)id);
						<p>Download poster here: <a href="@media.Url">Poster</a></p>
					}
					@if (CurrentPage.HasValue("additionalInfo"))
                    {
                        var id = Umbraco.TypedMedia(CurrentPage.GetPropertyValue("additionalInfo")).Id;
                        var media = Umbraco.TypedMedia((int)id);
                        <p>Download additional info here: <a href="@media.Url">Poster</a></p>
					}

					@CurrentPage.BodyText
				</section>
			</div>
            @Umbraco.RenderMacro("ContactCard", new { ContactParam = @CurrentPage.contact })
			<!-- Sidebar -->
			

					



		</div>
	</div>
</div>

root/Views/umbHomePage.cshtml
@inherits UmbracoTemplatePage
@{
    Layout = "umbLayout.cshtml";
}
@{ Html.RenderPartial("_banner"); }

<div id="main">
    <div id="content" class="container">
        @{   Html.RenderPartial("_seminarSlider"); }
    </div>
</div>
@{   Html.RenderPartial("_startSpots"); }

root/Views/umbLayout.cshtml
@using umbraco.NodeFactory
@inherits UmbracoTemplatePage
@{
    Layout = null;
    dynamic homePage = CurrentPage.AncestorsOrSelf(1).First();
    var n = new Node(CurrentPage.Id);
    string startpage = "";
    if (n.NodeTypeAlias == "umbHomePage")
    {
        startpage = "homepage";
    }
}
<!DOCTYPE html>
<html>
    <head>
        <title>@Umbraco.Field("title", "pageName") | @Umbraco.Field("siteName", recursive: true)</title>
        @*<script type="text/javascript">
            window.slimmage = {
                verbose: true };
</script>*@
<script src="/scripts/slimmage.settings.min.js"></script>
<script src="/scripts/slimmage.min.js"></script>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta name="description" content="" />
        <meta name="keywords" content="" />
       
   
        @*<link href='http://fonts.googleapis.com/css?family=Roboto:400,100,300,700,500,900' rel='stylesheet' type='text/css'>*@
        @*<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>*@
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
            <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
            <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.5.7/slick.css" />
            <link rel="stylesheet" type="text/css" href="~/slick/slick-theme.css" />
            <script type="text/javascript" src="~/slick/slick.min.js"></script>
            <script src="~/js/skel.min.js"></script>
            <script src="~/js/skel-panels.min.js"></script>
            <script src="~/js/init.js"></script>
            <script type="text/javascript"
                    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDZwfcrvcF3090T14ESGxpmhL3IYY5b1TU&sensor=false">
            </script>
            <script src="/scripts/Imagelightbox.min.js"></script>
            <noscript>
                <link rel="stylesheet" href="@Url.Content("~/css/skel-noscript.css")" />
                <link rel="stylesheet" href="@Url.Content("~/css/style.css")" />
                <link rel="stylesheet" href="@Url.Content("~/css/style-desktop.css")" />
            </noscript>
            <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
            <link rel="stylesheet" href="@Url.Content("~/css/style.css")" />
            <link rel="stylesheet" href="@Url.Content("~/css/style-desktop.css")" />
            <link rel="stylesheet" href="@Url.Content("~/css/lightbox.css")" />

            <script>
                (function (i, s, o, g, r, a, m) {
                    i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                        (i[r].q = i[r].q || []).push(arguments)
                    }, i[r].l = 1 * new Date(); a = s.createElement(o),
                        m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
                })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

                ga('create', '@Umbraco.Field("gaCode", recursive: true)', 'auto');
                ga('send', 'pageview');

            </script>
        </head>
    <body class="@startpage">



    @RenderBody()

    @{ Html.RenderPartial("_Social"); }


    </body>
    </html>

root/Views/umbNewsItem.cshtml
@inherits UmbracoTemplatePage
@{
    Layout = "umbLayout.cshtml";
    
    // If the editor has not explicitly provided the "Page title" property page 
    // then just show the name of the page otherwise show the provided title
    var pageTitle = string.IsNullOrWhiteSpace(CurrentPage.Title)
        ? CurrentPage.Name
        : CurrentPage.Title;
}
<div id="main-wrapper">
    <div id="main" class="container">
        <div class="row">
            <div class="9u skel-cell-mainContent">
                <div class="content content-left">
                    <!-- Content -->
                    <article class="is-page-content">
                        <header>
                            <h2>@pageTitle</h2>
                        </header>
                        <section>
                            @if (CurrentPage.HasValue("image"))
                            {
                                <span class="image image-full"><img src="@Umbraco.Media(CurrentPage.image.ToString()).umbracoFile" alt="" /></span>
                            }

                            @CurrentPage.BodyText
                        </section>                           
                    </article>
                    <!-- /Content -->
                </div>
            </div>
            <div class="3u">
                <div class="sidebar">
                    <!-- Sidebar -->
                    @{ Html.RenderPartial("umbLatestNewsWidget"); }
                    <!-- /Sidebar -->
                </div>
            </div>
        </div>
        <div class="row">
            <div class="12u">
                @{ Html.RenderPartial("umbFeatures"); }
            </div>
        </div>
    </div>
</div>
<!-- /Main -->

root/Views/umbNewsOverview.cshtml
@inherits UmbracoTemplatePage
@{
    Layout = "umbLayout.cshtml";

    // If the editor has not explicitly provided the "Page title" property page
    // then just show the name of the page otherwise show the provided title
    var pageTitle = string.IsNullOrWhiteSpace(CurrentPage.Title)
        ? CurrentPage.Name
        : CurrentPage.Title;

    // Model.Content is the current page that we're on
    // AncestorsOrSelf is all of the ancestors this page has in the tree
    // (1) means: go up to level 1 and stop looking for more ancestors when you get there
    // First() gets the first ancestor found (the home page, on level 1)
    var homePage = CurrentPage.AncestorsOrSelf(1).First();

    // Find all pages with document type alias umbNewsOverview
    // We do that using the plural, umbNewsOverviews (note the extra "s" in the end)
    // Then take the first one, as we know there will only be on news overview page
    var newsOverview = homePage.umbNewsOverviews.First();

    // Similar to above: find all pages with document type umbNewsItem under the news overview page
    // Then order them, first by publishDate (a property the editor can explicitly set on the news item)
    // and then by createDate, which is set by Umbraco automatically when a page gets created.
    var newsItems = newsOverview.umbNewsItems.OrderBy("publishDate desc, createDate desc").Take(5);

}
@{ Html.RenderPartial("_banner"); }
<!-- Main -->
<!-- Main -->
<div id="main">
    <div class="container">
        <div class="row">

            <!-- Content -->
            <div id="content" class="8u skel-cell-important">
                <section>
                    <header>
                        <h2>@pageTitle</h2>
                        <span class="byline">@CurrentPage.byline</span>
                        @if (CurrentPage.HasValue("image"))
                        {
                            <span class="image image-full"><img src="@Umbraco.Media(CurrentPage.image.ToString()).umbracoFile" alt="" /></span>
                        }

                        </header>
                        <article>
                            @foreach (var item in newsItems)
                            {

                                // If the editor has not explicitly provided the "Page title" property page
                                // then just show the name of the page otherwise show the provided title
                                var title = string.IsNullOrWhiteSpace(item.Title)
                                    ? item.Name
                                    : item.Title;


                                // If the editor has not explicitly set the publishDate property then show the create date
                                var dateTime = item.PublishDate == default(DateTime)
                                    ? item.CreateDate
                                    : item.PublishDate;

                                <section>
                                    <h3><a href="@item.Url">@title</a></h3>
                                    <span class="byline">@item.SubHeader</span>
                                    <ul class="meta">
                                        <li class="timestamp">@dateTime.ToString("f")</li>
                                    </ul>

                                    @if (item.HasValue("image"))
                                    {
                                        <a href="@item.Url" class="image image-full"><img src="@Umbraco.Media(item.image.ToString()).umbracoFile" alt="" /></a>
                                    }

                                    @Umbraco.Truncate(item.BodyText, 200)

                                    <a href="@item.Url" class="button">Continue Reading</a>
                                </section>
                            }
                        </article>
                        <!-- /Content -->
                </section>
            </div>

            <!-- Sidebar -->
            <div id="sidebar" class="4u">
                <section>
                    <header>
                        <h2>@CurrentPage.rightHeader</h2>
                    </header>
                    <div class="row">
                        @CurrentPage.rightText
                    <section class="6u">

                        <ul class="default">
                            <li><a href="#">Donec facilisis tempor</a></li>
                            <li><a href="#">Nulla convallis cursus</a></li>
                            <li><a href="#">Integer congue euismod</a></li>
                            <li><a href="#">Venenatis vulputate</a></li>
                            <li><a href="#">Morbi ligula volutpat</a></li>
                        </ul>
                    </section>
                    <section class="6u">
                        <ul class="default">
                            <li><a href="#">Donec facilisis tempor</a></li>
                            <li><a href="#">Nulla convallis cursus</a></li>
                            <li><a href="#">Integer congue euismod</a></li>
                            <li><a href="#">Venenatis vulputate</a></li>
                            <li><a href="#">Morbi ligula volutpat</a></li>
                        </ul>
                    </section>
                </div>
            </section>
            <section>
                <header>
                    <h2>Mauris vulputate</h2>
                </header>
                <ul class="style">
                    <li>
                        <p class="posted">May 21, 2014  |  (10 )  Comments</p>
                        <p><a href="#">Nullam non wisi a sem eleifend. Donec mattis libero eget urna. Pellentesque viverra enim.</a></p>
                    </li>
                    <li>
                        <p class="posted">May 18, 2014  |  (10 )  Comments</p>
                        <p><a href="#">Nullam non wisi a sem eleifend. Donec mattis libero eget urna. Pellentesque viverra enim.</a></p>
                    </li>
                </ul>
            </section>
        </div>

    </div>
</div>
</div>
<!-- /Main -->